apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: default
  labels:
    app.kubernetes.io/name: nginx
spec:
  ingressClassName: nginx
  rules:
  - host: "nginx.arpo.website"
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: nginx-service
            port:
              number: 80