apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: default
  labels:
    app.kubernetes.io/name: nginx
spec:
  # type: ClusterIP
  selector:
    # app.kubernetes.io/name: nginx
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80